name: Go

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]
jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-versions }}
    - name: Run go vet
      run: go vet ./...
    - name: Run go test
      run: GO111MODULE=on go test -v -race ./...
